# Simulation parameters
EXPERIMENT_TYPE: 'calibrate'
SIMULATION_TYPE: 'serial'

# Environment parameters
ENSEMBLE_COUNT: 100
REVERSAL_COUNT: 10
TRIAL_COUNT: 30

# ABC parameters
ABC_SAMPLE_COUNT: 10
ABC_ERROR_THRESHOLD: 0.01
TARGET_TYPE: 'guppy_serial'  # 'guppy_single', 'guppy_serial'
DISTANCE_TYPE: 'mse'  # 'mse', 'mae'

K_MIN: 0
K_MAX: 1
TAU_MIN: 0
TAU_MAX: 50
DECAY_MIN: 0
DECAY_MAX: 1